esphome:
  name: fujitsu
  friendly_name: fujitsu

external_components:
  - source: components

esp32:
  board: esp32dev

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 50%

climate:
  - platform: fujitsu_264
    name: "Fujitsu AC"
